var assert = require('assert');
const { handleHTMLData } = require('../HtmlToNodeHandler');

describe('Testing html page parsing to json data', function () {
    it('passing blank html page should return no data', function () {
        const htmlText = "<html></html>";
        const data = handleHTMLData(htmlText);
        assert.equal(data.length, 0);
    });

    it('passing valid HN html page should fetch all 30 records', function () {
        const htmlText = `<html op="news"><head><meta name="referrer" content="origin"><meta name="viewport" content="width=device-width, initial-scale=1.0"><link rel="stylesheet" type="text/css" href="news.css?XLcLbBo7vkKWFZeQcTnZ">
        <link rel="shortcut icon" href="favicon.ico">
      <link rel="alternate" type="application/rss+xml" title="RSS" href="rss">
    <title>Hacker News</title></head><body><center><table id="hnmain" border="0" cellpadding="0" cellspacing="0" width="85%" bgcolor="#f6f6ef">
    <tr><td bgcolor="#ff6600"><table border="0" cellpadding="0" cellspacing="0" width="100%" style="padding:2px"><tr><td style="width:18px;padding-right:4px"><a href="https://news.ycombinator.com"><img src="y18.gif" width="18" height="18" style="border:1px white solid;"></a></td>
              <td style="line-height:12pt; height:10px;"><span class="pagetop"><b class="hnname"><a href="news">Hacker News</a></b>
          <a href="newest">new</a> | <a href="front">past</a> | <a href="newcomments">comments</a> | <a href="ask">ask</a> | <a href="show">show</a> | <a href="jobs">jobs</a> | <a href="submit">submit</a>
     </span></td><td style="text-align:right;padding-right:4px;"><span class="pagetop">
                          <a href="login?goto=news%3Fp%3D1">login</a>
                      </span></td>
          </tr></table></td></tr>
<tr id="pagespace" title="" style="height:10px"></tr><tr><td><table border="0" cellpadding="0" cellspacing="0" class="itemlist">
          <tr class='athing' id='20578591'>
  <td align="right" valign="top" class="title"><span class="rank">1.</span></td>      <td valign="top" class="votelinks"><center><a id='up_20578591' href='vote?id=20578591&amp;how=up&amp;goto=news%3Fp%3D1'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="http://www.planetary.org/blogs/jason-davis/lightsail-2-successful-flight-by-light.html" class="storylink">LightSail 2 Spacecraft Successfully Demonstrates Flight by Light</a><span class="sitebit comhead"> (<a href="from?site=planetary.org"><span class="sitestr">planetary.org</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
    <span class="score" id="score_20578591">84 points</span> by <a href="user?id=spazz" class="hnuser">spazz</a> <span class="age"><a href="item?id=20578591">1 hour ago</a></span> <span id="unv_20578591"></span> | <a href="hide?id=20578591&amp;goto=news%3Fp%3D1">hide</a> | <a href="item?id=20578591">31&nbsp;comments</a>              </td></tr>
  <tr class="spacer" style="height:5px"></tr>
            <tr class='athing' id='20574883'>
  <td align="right" valign="top" class="title"><span class="rank">2.</span></td>      <td valign="top" class="votelinks"><center><a id='up_20574883' href='vote?id=20574883&amp;how=up&amp;goto=news%3Fp%3D1'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://www.designweek.co.uk/issues/22-28-july-2019/chelsea-westminster-hospital-arts-research/" class="storylink">Filling hospitals with art reduces patient stress, anxiety and pain</a><span class="sitebit comhead"> (<a href="from?site=designweek.co.uk"><span class="sitestr">designweek.co.uk</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
    <span class="score" id="score_20574883">335 points</span> by <a href="user?id=rchaudhary" class="hnuser">rchaudhary</a> <span class="age"><a href="item?id=20574883">7 hours ago</a></span> <span id="unv_20574883"></span> | <a href="hide?id=20574883&amp;goto=news%3Fp%3D1">hide</a> | <a href="item?id=20574883">95&nbsp;comments</a>              </td></tr>
  <tr class="spacer" style="height:5px"></tr>
            <tr class='athing' id='20578850'>
  <td align="right" valign="top" class="title"><span class="rank">3.</span></td>      <td valign="top" class="votelinks"><center><a id='up_20578850' href='vote?id=20578850&amp;how=up&amp;goto=news%3Fp%3D1'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="item?id=20578850" class="storylink">Launch HN: Hatchways (YC S19) – Internships Instead of Interviews</a></td></tr><tr><td colspan="2"></td><td class="subtext">
    <span class="score" id="score_20578850">36 points</span> by <a href="user?id=jaclynmling" class="hnuser">jaclynmling</a> <span class="age"><a href="item?id=20578850">54 minutes ago</a></span> <span id="unv_20578850"></span> | <a href="hide?id=20578850&amp;goto=news%3Fp%3D1">hide</a> | <a href="item?id=20578850">10&nbsp;comments</a>              </td></tr>
  <tr class="spacer" style="height:5px"></tr>
            <tr class='athing' id='20574992'>
  <td align="right" valign="top" class="title"><span class="rank">4.</span></td>      <td valign="top" class="votelinks"><center><a id='up_20574992' href='vote?id=20574992&amp;how=up&amp;goto=news%3Fp%3D1'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://www.balena.io/blog/build-a-raspberry-pi-powered-train-station-oled-sign-for-your-desk/" class="storylink">A Raspberry Pi-powered live train station sign</a><span class="sitebit comhead"> (<a href="from?site=balena.io"><span class="sitestr">balena.io</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
    <span class="score" id="score_20574992">429 points</span> by <a href="user?id=chrisys" class="hnuser">chrisys</a> <span class="age"><a href="item?id=20574992">7 hours ago</a></span> <span id="unv_20574992"></span> | <a href="hide?id=20574992&amp;goto=news%3Fp%3D1">hide</a> | <a href="item?id=20574992">109&nbsp;comments</a>              </td></tr>
  <tr class="spacer" style="height:5px"></tr>
            <tr class='athing' id='20576503'>
  <td align="right" valign="top" class="title"><span class="rank">5.</span></td>      <td valign="top" class="votelinks"><center><a id='up_20576503' href='vote?id=20576503&amp;how=up&amp;goto=news%3Fp%3D1'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://fuse.wikichip.org/news/2567/tsmc-talks-7nm-5nm-yield-and-next-gen-5g-and-hpc-packaging/" class="storylink">TSMC Talks 7nm, 5nm, Yield, and Next-Gen 5G and HPC Packaging</a><span class="sitebit comhead"> (<a href="from?site=wikichip.org"><span class="sitestr">wikichip.org</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
    <span class="score" id="score_20576503">121 points</span> by <a href="user?id=rbanffy" class="hnuser">rbanffy</a> <span class="age"><a href="item?id=20576503">4 hours ago</a></span> <span id="unv_20576503"></span> | <a href="hide?id=20576503&amp;goto=news%3Fp%3D1">hide</a> | <a href="item?id=20576503">43&nbsp;comments</a>              </td></tr>
  <tr class="spacer" style="height:5px"></tr>
            <tr class='athing' id='20563745'>
  <td align="right" valign="top" class="title"><span class="rank">6.</span></td>      <td valign="top" class="votelinks"><center><a id='up_20563745' href='vote?id=20563745&amp;how=up&amp;goto=news%3Fp%3D1'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="http://jordan-vincent.com/night-under-the-stars" class="storylink">A Look at Overnight Stays at US National Parks</a><span class="sitebit comhead"> (<a href="from?site=jordan-vincent.com"><span class="sitestr">jordan-vincent.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
    <span class="score" id="score_20563745">154 points</span> by <a href="user?id=skilled" class="hnuser">skilled</a> <span class="age"><a href="item?id=20563745">5 hours ago</a></span> <span id="unv_20563745"></span> | <a href="hide?id=20563745&amp;goto=news%3Fp%3D1">hide</a> | <a href="item?id=20563745">65&nbsp;comments</a>              </td></tr>
  <tr class="spacer" style="height:5px"></tr>
            <tr class='athing' id='20577334'>
  <td align="right" valign="top" class="title"><span class="rank">7.</span></td>      <td valign="top" class="votelinks"><center><a id='up_20577334' href='vote?id=20577334&amp;how=up&amp;goto=news%3Fp%3D1'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://argumatronic.com/posts/2019-06-21-algebra-cheatsheet.html" class="storylink">A Brief Guide to a Few Algebraic Structures</a><span class="sitebit comhead"> (<a href="from?site=argumatronic.com"><span class="sitestr">argumatronic.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
    <span class="score" id="score_20577334">71 points</span> by <a href="user?id=edgarvm" class="hnuser">edgarvm</a> <span class="age"><a href="item?id=20577334">3 hours ago</a></span> <span id="unv_20577334"></span> | <a href="hide?id=20577334&amp;goto=news%3Fp%3D1">hide</a> | <a href="item?id=20577334">1&nbsp;comment</a>              </td></tr>
  <tr class="spacer" style="height:5px"></tr>
            <tr class='athing' id='20562291'>
  <td align="right" valign="top" class="title"><span class="rank">8.</span></td>      <td valign="top" class="votelinks"><center><a id='up_20562291' href='vote?id=20562291&amp;how=up&amp;goto=news%3Fp%3D1'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://www.sfchronicle.com/business/article/Most-internet-service-providers-are-gone-Sonic-14188418.php" class="storylink">Most internet service providers are gone. Sonic has survived – and thrived</a><span class="sitebit comhead"> (<a href="from?site=sfchronicle.com"><span class="sitestr">sfchronicle.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
    <span class="score" id="score_20562291">37 points</span> by <a href="user?id=CaliforniaKarl" class="hnuser">CaliforniaKarl</a> <span class="age"><a href="item?id=20562291">2 hours ago</a></span> <span id="unv_20562291"></span> | <a href="hide?id=20562291&amp;goto=news%3Fp%3D1">hide</a> | <a href="item?id=20562291">16&nbsp;comments</a>              </td></tr>
  <tr class="spacer" style="height:5px"></tr>
            <tr class='athing' id='20574711'>
  <td align="right" valign="top" class="title"><span class="rank">9.</span></td>      <td valign="top" class="votelinks"><center><a id='up_20574711' href='vote?id=20574711&amp;how=up&amp;goto=news%3Fp%3D1'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://www.bbc.co.uk/news/uk-england-49164316" class="storylink">Tree planting: Where can I do it and which type is best?</a><span class="sitebit comhead"> (<a href="from?site=bbc.co.uk"><span class="sitestr">bbc.co.uk</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
    <span class="score" id="score_20574711">228 points</span> by <a href="user?id=pmoriarty" class="hnuser">pmoriarty</a> <span class="age"><a href="item?id=20574711">7 hours ago</a></span> <span id="unv_20574711"></span> | <a href="hide?id=20574711&amp;goto=news%3Fp%3D1">hide</a> | <a href="item?id=20574711">150&nbsp;comments</a>              </td></tr>
  <tr class="spacer" style="height:5px"></tr>
            <tr class='athing' id='20564106'>
  <td align="right" valign="top" class="title"><span class="rank">10.</span></td>      <td valign="top" class="votelinks"><center><a id='up_20564106' href='vote?id=20564106&amp;how=up&amp;goto=news%3Fp%3D1'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://www.nationalgeographic.com/science/phenomena/2016/01/07/the-fantastically-strange-origin-of-most-coal-on-earth/" class="storylink">The Origin of Most Coal on Earth (2016)</a><span class="sitebit comhead"> (<a href="from?site=nationalgeographic.com"><span class="sitestr">nationalgeographic.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
    <span class="score" id="score_20564106">60 points</span> by <a href="user?id=lordnacho" class="hnuser">lordnacho</a> <span class="age"><a href="item?id=20564106">4 hours ago</a></span> <span id="unv_20564106"></span> | <a href="hide?id=20564106&amp;goto=news%3Fp%3D1">hide</a> | <a href="item?id=20564106">27&nbsp;comments</a>              </td></tr>
  <tr class="spacer" style="height:5px"></tr>
            <tr class='athing' id='20577660'>
  <td align="right" valign="top" class="title"><span class="rank">11.</span></td>      <td valign="top" class="votelinks"><center><a id='up_20577660' href='vote?id=20577660&amp;how=up&amp;goto=news%3Fp%3D1'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="http://scheme2006.cs.uchicago.edu/11-ghuloum.pdf" class="storylink">An Incremental Approach to Compiler Construction (2006) [pdf]</a><span class="sitebit comhead"> (<a href="from?site=uchicago.edu"><span class="sitestr">uchicago.edu</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
    <span class="score" id="score_20577660">40 points</span> by <a href="user?id=rspivak" class="hnuser">rspivak</a> <span class="age"><a href="item?id=20577660">2 hours ago</a></span> <span id="unv_20577660"></span> | <a href="hide?id=20577660&amp;goto=news%3Fp%3D1">hide</a> | <a href="item?id=20577660">1&nbsp;comment</a>              </td></tr>
  <tr class="spacer" style="height:5px"></tr>
            <tr class='athing' id='20574542'>
  <td align="right" valign="top" class="title"><span class="rank">12.</span></td>      <td valign="top" class="votelinks"><center><a id='up_20574542' href='vote?id=20574542&amp;how=up&amp;goto=news%3Fp%3D1'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://lkml.org/lkml/2019/7/30/1399" class="storylink">Implement mechanism to wait on any of several futexes</a><span class="sitebit comhead"> (<a href="from?site=lkml.org"><span class="sitestr">lkml.org</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
    <span class="score" id="score_20574542">204 points</span> by <a href="user?id=yankcrime" class="hnuser">yankcrime</a> <span class="age"><a href="item?id=20574542">8 hours ago</a></span> <span id="unv_20574542"></span> | <a href="hide?id=20574542&amp;goto=news%3Fp%3D1">hide</a> | <a href="item?id=20574542">89&nbsp;comments</a>              </td></tr>
  <tr class="spacer" style="height:5px"></tr>
            <tr class='athing' id='20578766'>
  <td align="right" valign="top" class="title"><span class="rank">13.</span></td>      <td valign="top" class="votelinks"><center><a id='up_20578766' href='vote?id=20578766&amp;how=up&amp;goto=news%3Fp%3D1'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://twitter.com/LauraSullivaNPR/status/1156617951245721601" class="storylink">Equifax removed the $125 claim payout option after millions submitted claims</a><span class="sitebit comhead"> (<a href="from?site=twitter.com"><span class="sitestr">twitter.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
    <span class="score" id="score_20578766">50 points</span> by <a href="user?id=pavel_lishin" class="hnuser">pavel_lishin</a> <span class="age"><a href="item?id=20578766">1 hour ago</a></span> <span id="unv_20578766"></span> | <a href="hide?id=20578766&amp;goto=news%3Fp%3D1">hide</a> | <a href="item?id=20578766">14&nbsp;comments</a>              </td></tr>
  <tr class="spacer" style="height:5px"></tr>
            <tr class='athing' id='20574473'>
  <td align="right" valign="top" class="title"><span class="rank">14.</span></td>      <td valign="top" class="votelinks"><center><a id='up_20574473' href='vote?id=20574473&amp;how=up&amp;goto=news%3Fp%3D1'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://www.thedrive.com/the-war-zone/29218/these-images-of-an-f-22-raptors-crumbling-radar-absorbent-skin-are-fascinating" class="storylink">An F-22 Raptor’s Crumbling Radar Absorbent Skin</a><span class="sitebit comhead"> (<a href="from?site=thedrive.com"><span class="sitestr">thedrive.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
    <span class="score" id="score_20574473">144 points</span> by <a href="user?id=Alupis" class="hnuser">Alupis</a> <span class="age"><a href="item?id=20574473">8 hours ago</a></span> <span id="unv_20574473"></span> | <a href="hide?id=20574473&amp;goto=news%3Fp%3D1">hide</a> | <a href="item?id=20574473">142&nbsp;comments</a>              </td></tr>
  <tr class="spacer" style="height:5px"></tr>
            <tr class='athing' id='20576791'>
  <td align="right" valign="top" class="title"><span class="rank">15.</span></td>      <td valign="top" class="votelinks"><center><a id='up_20576791' href='vote?id=20576791&amp;how=up&amp;goto=news%3Fp%3D1'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://spectrum.ieee.org/tech-talk/semiconductors/processors/first-programmable-memristor-computer" class="storylink">First Programmable Memristor Computer</a><span class="sitebit comhead"> (<a href="from?site=ieee.org"><span class="sitestr">ieee.org</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
    <span class="score" id="score_20576791">43 points</span> by <a href="user?id=headalgorithm" class="hnuser">headalgorithm</a> <span class="age"><a href="item?id=20576791">4 hours ago</a></span> <span id="unv_20576791"></span> | <a href="hide?id=20576791&amp;goto=news%3Fp%3D1">hide</a> | <a href="item?id=20576791">18&nbsp;comments</a>              </td></tr>
  <tr class="spacer" style="height:5px"></tr>
            <tr class='athing' id='20575502'>
  <td align="right" valign="top" class="title"><span class="rank">16.</span></td>      <td valign="top" class="votelinks"><center><a id='up_20575502' href='vote?id=20575502&amp;how=up&amp;goto=news%3Fp%3D1'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://www.zdnet.com/article/you-can-go-your-own-graph-database-way-dgraph-secures-115m-to-pursue-its-opinionated-path/" class="storylink">Graph database reinvented: Dgraph gets $11.5M to pursue unique, opinionated path</a><span class="sitebit comhead"> (<a href="from?site=zdnet.com"><span class="sitestr">zdnet.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
    <span class="score" id="score_20575502">116 points</span> by <a href="user?id=bryanrasmussen" class="hnuser">bryanrasmussen</a> <span class="age"><a href="item?id=20575502">6 hours ago</a></span> <span id="unv_20575502"></span> | <a href="hide?id=20575502&amp;goto=news%3Fp%3D1">hide</a> | <a href="item?id=20575502">42&nbsp;comments</a>              </td></tr>
  <tr class="spacer" style="height:5px"></tr>
            <tr class='athing' id='20574944'>
  <td align="right" valign="top" class="title"><span class="rank">17.</span></td>      <td valign="top" class="votelinks"><center><a id='up_20574944' href='vote?id=20574944&amp;how=up&amp;goto=news%3Fp%3D1'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://www.moderntreasury.com/journal/how-to-build-an-insurance-company" class="storylink">Building Payments for an Insurance Startup</a><span class="sitebit comhead"> (<a href="from?site=moderntreasury.com"><span class="sitestr">moderntreasury.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
    <span class="score" id="score_20574944">108 points</span> by <a href="user?id=saarons" class="hnuser">saarons</a> <span class="age"><a href="item?id=20574944">7 hours ago</a></span> <span id="unv_20574944"></span> | <a href="hide?id=20574944&amp;goto=news%3Fp%3D1">hide</a> | <a href="item?id=20574944">23&nbsp;comments</a>              </td></tr>
  <tr class="spacer" style="height:5px"></tr>
            <tr class='athing' id='20579010'>
  <td align="right" valign="top" class="title"><span class="rank">18.</span></td>      <td valign="top" class="votelinks"><center><a id='up_20579010' href='vote?id=20579010&amp;how=up&amp;goto=news%3Fp%3D1'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://www.theguardian.com/australia-news/2019/jul/28/erased-from-history-how-sydney-destroyed-its-trams-for-love-of-the-car" class="storylink" rel="nofollow">How Sydney destroyed its trams for love of the car</a><span class="sitebit comhead"> (<a href="from?site=theguardian.com"><span class="sitestr">theguardian.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
    <span class="score" id="score_20579010">3 points</span> by <a href="user?id=oska" class="hnuser">oska</a> <span class="age"><a href="item?id=20579010">30 minutes ago</a></span> <span id="unv_20579010"></span> | <a href="hide?id=20579010&amp;goto=news%3Fp%3D1">hide</a> | <a href="item?id=20579010">discuss</a>              </td></tr>
  <tr class="spacer" style="height:5px"></tr>
            <tr class='athing' id='20577416'>
  <td align="right" valign="top" class="title"><span class="rank">19.</span></td>      <td valign="top" class="votelinks"><center><a id='up_20577416' href='vote?id=20577416&amp;how=up&amp;goto=news%3Fp%3D1'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://twitter.com/Joe8Bit/status/1156312965265707013" class="storylink">Why does unsubscribing from a newsletter take “a few days”?</a><span class="sitebit comhead"> (<a href="from?site=twitter.com"><span class="sitestr">twitter.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
    <span class="score" id="score_20577416">112 points</span> by <a href="user?id=scop" class="hnuser">scop</a> <span class="age"><a href="item?id=20577416">3 hours ago</a></span> <span id="unv_20577416"></span> | <a href="hide?id=20577416&amp;goto=news%3Fp%3D1">hide</a> | <a href="item?id=20577416">45&nbsp;comments</a>              </td></tr>
  <tr class="spacer" style="height:5px"></tr>
            <tr class='athing' id='20572705'>
  <td align="right" valign="top" class="title"><span class="rank">20.</span></td>      <td valign="top" class="votelinks"><center><a id='up_20572705' href='vote?id=20572705&amp;how=up&amp;goto=news%3Fp%3D1'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://en.wikipedia.org/wiki/Kriegspiel_(chess)" class="storylink">Kriegspiel</a><span class="sitebit comhead"> (<a href="from?site=wikipedia.org"><span class="sitestr">wikipedia.org</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
    <span class="score" id="score_20572705">266 points</span> by <a href="user?id=tosh" class="hnuser">tosh</a> <span class="age"><a href="item?id=20572705">13 hours ago</a></span> <span id="unv_20572705"></span> | <a href="hide?id=20572705&amp;goto=news%3Fp%3D1">hide</a> | <a href="item?id=20572705">78&nbsp;comments</a>              </td></tr>
  <tr class="spacer" style="height:5px"></tr>
            <tr class='athing' id='20577164'>
  <td align="right" valign="top" class="title"><span class="rank">21.</span></td>      <td valign="top" class="votelinks"><center><a id='up_20577164' href='vote?id=20577164&amp;how=up&amp;goto=news%3Fp%3D1'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://www.theatlantic.com/science/archive/2019/07/cat-birds-australia/595048/" class="storylink">A Single Male Cat’s Reign of Terror</a><span class="sitebit comhead"> (<a href="from?site=theatlantic.com"><span class="sitestr">theatlantic.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
    <span class="score" id="score_20577164">20 points</span> by <a href="user?id=pseudolus" class="hnuser">pseudolus</a> <span class="age"><a href="item?id=20577164">3 hours ago</a></span> <span id="unv_20577164"></span> | <a href="hide?id=20577164&amp;goto=news%3Fp%3D1">hide</a> | <a href="item?id=20577164">22&nbsp;comments</a>              </td></tr>
  <tr class="spacer" style="height:5px"></tr>
            <tr class='athing' id='20574874'>
  <td align="right" valign="top" class="title"><span class="rank">22.</span></td>      <td valign="top" class="votelinks"><center><a id='up_20574874' href='vote?id=20574874&amp;how=up&amp;goto=news%3Fp%3D1'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://www.drama.app/beta" class="storylink">Drama – Draw user interfaces and create interactive prototypes</a><span class="sitebit comhead"> (<a href="from?site=drama.app"><span class="sitestr">drama.app</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
    <span class="score" id="score_20574874">131 points</span> by <a href="user?id=robenkleene" class="hnuser">robenkleene</a> <span class="age"><a href="item?id=20574874">7 hours ago</a></span> <span id="unv_20574874"></span> | <a href="hide?id=20574874&amp;goto=news%3Fp%3D1">hide</a> | <a href="item?id=20574874">38&nbsp;comments</a>              </td></tr>
  <tr class="spacer" style="height:5px"></tr>
            <tr class='athing' id='20574920'>
  <td align="right" valign="top" class="title"><span class="rank">23.</span></td>      <td valign="top" class="votelinks"><center><a id='up_20574920' href='vote?id=20574920&amp;how=up&amp;goto=news%3Fp%3D1'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://www.nytimes.com/2019/07/31/business/how-phones-made-the-world-your-office-like-it-or-not.html" class="storylink">Phones Made the World an Office, Like It or Not</a><span class="sitebit comhead"> (<a href="from?site=nytimes.com"><span class="sitestr">nytimes.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
    <span class="score" id="score_20574920">47 points</span> by <a href="user?id=DamnInteresting" class="hnuser">DamnInteresting</a> <span class="age"><a href="item?id=20574920">7 hours ago</a></span> <span id="unv_20574920"></span> | <a href="hide?id=20574920&amp;goto=news%3Fp%3D1">hide</a> | <a href="item?id=20574920">23&nbsp;comments</a>              </td></tr>
  <tr class="spacer" style="height:5px"></tr>
            <tr class='athing' id='20563942'>
  <td align="right" valign="top" class="title"><span class="rank">24.</span></td>      <td valign="top" class="votelinks"><center><a id='up_20563942' href='vote?id=20563942&amp;how=up&amp;goto=news%3Fp%3D1'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://habr.com/en/post/440610/" class="storylink" rel="nofollow">Introduce Static Analysis in the Process, Don't Just Search for Bugs with It</a><span class="sitebit comhead"> (<a href="from?site=habr.com"><span class="sitestr">habr.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
    <span class="score" id="score_20563942">5 points</span> by <a href="user?id=ingve" class="hnuser">ingve</a> <span class="age"><a href="item?id=20563942">1 hour ago</a></span> <span id="unv_20563942"></span> | <a href="hide?id=20563942&amp;goto=news%3Fp%3D1">hide</a> | <a href="item?id=20563942">discuss</a>              </td></tr>
  <tr class="spacer" style="height:5px"></tr>
            <tr class='athing' id='20574797'>
  <td align="right" valign="top" class="title"><span class="rank">25.</span></td>      <td valign="top" class="votelinks"><center><a id='up_20574797' href='vote?id=20574797&amp;how=up&amp;goto=news%3Fp%3D1'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://evilmartians.com/chronicles/lefthook-knock-your-teams-code-back-into-shape" class="storylink">Lefthook: Knock your team’s code back into shape</a><span class="sitebit comhead"> (<a href="from?site=evilmartians.com"><span class="sitestr">evilmartians.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
    <span class="score" id="score_20574797">85 points</span> by <a href="user?id=ingve" class="hnuser">ingve</a> <span class="age"><a href="item?id=20574797">7 hours ago</a></span> <span id="unv_20574797"></span> | <a href="hide?id=20574797&amp;goto=news%3Fp%3D1">hide</a> | <a href="item?id=20574797">38&nbsp;comments</a>              </td></tr>
  <tr class="spacer" style="height:5px"></tr>
            <tr class='athing' id='20577154'>
  <td align="right" valign="top" class="title"><span class="rank">26.</span></td>      <td valign="top" class="votelinks"><center><a id='up_20577154' href='vote?id=20577154&amp;how=up&amp;goto=news%3Fp%3D1'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="http://dtrace.org/blogs/bmc/2019/07/31/ex-joyeur/" class="storylink">Ex-Joyeur</a><span class="sitebit comhead"> (<a href="from?site=dtrace.org"><span class="sitestr">dtrace.org</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
    <span class="score" id="score_20577154">45 points</span> by <a href="user?id=skreuzer" class="hnuser">skreuzer</a> <span class="age"><a href="item?id=20577154">2 hours ago</a></span> <span id="unv_20577154"></span> | <a href="hide?id=20577154&amp;goto=news%3Fp%3D1">hide</a> | <a href="item?id=20577154">6&nbsp;comments</a>              </td></tr>
  <tr class="spacer" style="height:5px"></tr>
            <tr class='athing' id='20556982'>
  <td align="right" valign="top" class="title"><span class="rank">27.</span></td>      <td valign="top" class="votelinks"><center><a id='up_20556982' href='vote?id=20556982&amp;how=up&amp;goto=news%3Fp%3D1'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://www.neh.gov/article/honest-fault" class="storylink">Honest to a Fault: Pepys’s journals bear witness to events large and small</a><span class="sitebit comhead"> (<a href="from?site=neh.gov"><span class="sitestr">neh.gov</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
    <span class="score" id="score_20556982">12 points</span> by <a href="user?id=Petiver" class="hnuser">Petiver</a> <span class="age"><a href="item?id=20556982">3 hours ago</a></span> <span id="unv_20556982"></span> | <a href="hide?id=20556982&amp;goto=news%3Fp%3D1">hide</a> | <a href="item?id=20556982">2&nbsp;comments</a>              </td></tr>
  <tr class="spacer" style="height:5px"></tr>
            <tr class='athing' id='20575463'>
  <td align="right" valign="top" class="title"><span class="rank">28.</span></td>      <td valign="top" class="votelinks"><center><a id='up_20575463' href='vote?id=20575463&amp;how=up&amp;goto=news%3Fp%3D1'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://www.latimes.com/politics/story/2019-07-31/trump-administration-drugs-canada" class="storylink">U.S. to set up plan aimed at allowing prescription drugs from Canada</a><span class="sitebit comhead"> (<a href="from?site=latimes.com"><span class="sitestr">latimes.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
    <span class="score" id="score_20575463">147 points</span> by <a href="user?id=ilamont" class="hnuser">ilamont</a> <span class="age"><a href="item?id=20575463">6 hours ago</a></span> <span id="unv_20575463"></span> | <a href="hide?id=20575463&amp;goto=news%3Fp%3D1">hide</a> | <a href="item?id=20575463">195&nbsp;comments</a>              </td></tr>
  <tr class="spacer" style="height:5px"></tr>
            <tr class='athing' id='20576655'>
  <td align="right" valign="top" class="title"><span class="rank">29.</span></td>      <td valign="top" class="votelinks"><center><a id='up_20576655' href='vote?id=20576655&amp;how=up&amp;goto=news%3Fp%3D1'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://www.outsideonline.com/2399736/impossible-foods-beyond-meat-alt-meat" class="storylink">The Beginning of the End of the Beef Industry?</a><span class="sitebit comhead"> (<a href="from?site=outsideonline.com"><span class="sitestr">outsideonline.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
    <span class="score" id="score_20576655">91 points</span> by <a href="user?id=EastLondonCoder" class="hnuser">EastLondonCoder</a> <span class="age"><a href="item?id=20576655">4 hours ago</a></span> <span id="unv_20576655"></span> | <a href="hide?id=20576655&amp;goto=news%3Fp%3D1">hide</a> | <a href="item?id=20576655">152&nbsp;comments</a>              </td></tr>
  <tr class="spacer" style="height:5px"></tr>
            <tr class='athing' id='20576845'>
  <td align="right" valign="top" class="title"><span class="rank">30.</span></td>      <td valign="top" class="votelinks"><center><a id='up_20576845' href='vote?id=20576845&amp;how=up&amp;goto=news%3Fp%3D1'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://blog.golang.org/why-generics" class="storylink">Why Generics?</a><span class="sitebit comhead"> (<a href="from?site=golang.org"><span class="sitestr">golang.org</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
    <span class="score" id="score_20576845">170 points</span> by <a href="user?id=johnvega" class="hnuser">johnvega</a> <span class="age"><a href="item?id=20576845">3 hours ago</a></span> <span id="unv_20576845"></span> | <a href="hide?id=20576845&amp;goto=news%3Fp%3D1">hide</a> | <a href="item?id=20576845">153&nbsp;comments</a>              </td></tr>
  <tr class="spacer" style="height:5px"></tr>
        <tr class="morespace" style="height:10px"></tr><tr><td colspan="2"></td><td class="title"><a href="news?p=2" class="morelink" rel="next">More</a></td></tr>
</table>
</td></tr>
<tr><td><img src="s.gif" height="10" width="0"><table width="100%" cellspacing="0" cellpadding="1"><tr><td bgcolor="#ff6600"></td></tr></table><br><center><a href="https://www.startupschool.org">
    Startup School is now on! You can still get in till August&nbsp;4.
  </a></center><br><center><span class="yclinks"><a href="newsguidelines.html">Guidelines</a>
    | <a href="newsfaq.html">FAQ</a>
    | <a href="mailto:hn@ycombinator.com">Support</a>
    | <a href="https://github.com/HackerNews/API">API</a>
    | <a href="security.html">Security</a>
    | <a href="lists">Lists</a>
    | <a href="bookmarklet.html" rel="nofollow">Bookmarklet</a>
    | <a href="http://www.ycombinator.com/legal/">Legal</a>
    | <a href="http://www.ycombinator.com/apply/">Apply to YC</a>
    | <a href="mailto:hn@ycombinator.com">Contact</a></span><br><br><form method="get" action="//hn.algolia.com/">Search:
      <input type="text" name="q" value="" size="17" autocorrect="off" spellcheck="false" autocapitalize="off" autocomplete="false"></form>
        </center></td></tr>
  </table></center></body><script type='text/javascript' src='hn.js?XLcLbBo7vkKWFZeQcTnZ'></script>
</html>`;
        const data = handleHTMLData(htmlText);
        console.log(data);
        assert.equal(data.length, 30);
    });
});